
ati_nano17_ft:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  sensor_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ati_nano17_ft_sensor_joint
    pid: {p: 100.0, i: 0.0, d: 1.0}
